### PR TITLE
swap asert for args-expect

### PR DESCRIPTION
**Pull request by stevenvachon**
as it's simpler and smaller in file size when browserified.

### CODE REVIEW

**Comment by stevenvachon** [comment]
The other promise-\* libs should be updated to use this same dependency.

**Comment by stevenvachon** [comment]
@yoshuawuyts would it be too much to ask to be added to the npm package contributors list so that I can make releases?

**Comment by yoshuawuyts** [comment]
Cool, added you as a contributor on npm.

**Comment by yoshuawuyts** [comment]
Also: if we're opting to byte-shave I think I'd opt for a small function that uses a familiar interface to do assertions rather than pull in an extra module; e.g.

``` js
function assertEqual (first, second, msg) {
   if (first != second) {
    msg = msg || 'expected ' + first + ' to be ' + second
    throw new Error(msg)
  } 
}
```

**Comment by stevenvachon** [comment]
But then if we include both promise-each and promise-map, we'll have duplicated assertion functions

**Comment by stevenvachon** [comment]
Thanks for making me a contributor!

**Comment by yoshuawuyts** [comment]
I did some benchmarking and browserify's `assert` weighs in at `3.81kb` where `args-expect` sits at `2.43kb`, the gap is probably even smaller after minification. I honestly don't think `1.38kb` of overhead warrants deviating from the stdlib.

**edit**: also: no problem! Happy that you're interested in these modules :grin:

**Comment by stevenvachon** [comment]
Hmm, so to use browserify's assert, we would need to add that as a dependency? I'm no expert with browserify -- I'd just used its command line to compile.

**Comment by yoshuawuyts** [comment]
Nope, it does that for you automatically on compile. No changes have to be made to support it (':

**Comment by stevenvachon** [comment]
I'm not sure why it compiled to ~12kb for me, then (?)

**Comment by yoshuawuyts** [comment]
I think you looked at the non-gzipped value.

When looking at file size the compressed value is the accurate representation of what is transferred over the wire. The more files are included, the smaller the overhead of a single file will be. That's why in this case I pointed out that the files were measured stand-alone, before minification; when minified and included in a bundle the overhead will be even smaller.

**Comment by stevenvachon** [comment]
I'm thinking that I might try collaborating with the args-expect developer to make it more modular. I'd like to use it in other projects but would like pieces of it to be used in smaller libraries like this one. If I were to write an absolutely tiny "expect-function" package, we could use that specifically if you'd be ok with that.

**Comment by stevenvachon** [comment]
I think that this should be written in TypeScript if you're so concerned with input types. Loading an assertion library is overkill.

**Comment by yoshuawuyts** [comment]
I don't like your tone - have fun writing your own stuff

**Comment by stevenvachon** [comment]
Perhaps you've forgotten that we've already worked together on this. Are you drunk? If not and this is how you feel, please remove my co-ownership from npm.

**Comment by yoshuawuyts** [comment]
Nah, I received this email without context and didn't like the sound of it
- only recently switched to email notifications. If you don't want to be
involved feel free to remove yourself

**Comment by stevenvachon** [comment]
I want to improve it, as I did in 2015.

**Pull request closed without merging**
